# Generated by Django 6.0.3 on 2026-05-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientwaitlist_providerwaitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwaitlist',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientwaitlist',
            name='country',
            field=models.CharField(default='Brasil', max_length=100),
        ),
        migrations.AddField(
            model_name='providerwaitlist',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerwaitlist',
            name='country',
            field=models.CharField(default='Brasil', max_length=100),
        ),
    ]
